services:
  blackjack-frontend:
    image: ghcr.io/sahinakkaya/blackjack-frontend:main
    env_file:
      - .env.blackjack-frontend
    ports: 
      - "8432:8000"
    

  blackjack-backend:
    image: ghcr.io/sahinakkaya/blackjack-backend:main
    env_file:
      - .env.blackjack-backend
    ports: 
      - "8433:3000"
