services:
  blackjack-frontend:
    image: ghcr.io/sahinakkaya/blackjack-frontend:main
    ports: 
      - "8432:3000"
    

  blackjack-backend:
    image: ghcr.io/sahinakkaya/blackjack-backend:main
    env_file:
      - .env.backend
    ports: 
      - "8433:8000"
